title: Becky Eden # your name (or website title) here
logo: "/images/Becky.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a student in Geospatial Technology and will graduate with a Master's degree
  in Summer of 2022.  I have a facination in creating maps that can tell the viewer
  what they need to know about a topic.  The saying "A picture is worth a thousand
  words" is what I aim for with my map creations.
  <br><br>
  I am currently an Accounting Manager and have worked in Accounting for over 
  ten years.  I enjoy working with numbers as much as I enjoy creating maps.  I 
  would love to find a position that enables me to do both.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
